---
# tasks/mongodb.yml: MongoDB configuration for RocketChat.Ansible
  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"

  - name: Add MongoDB GPG key
    apt_key:
        url: "https://www.mongodb.org/static/pgp/server-4.4.asc"  # URL de la clé publique MongoDB
        state: present
    tags: repo

  - name: Ensure the MongoDB repository key has been imported
    apt_key:
      keyserver: "{{ rocket_chat_mongodb_keyserver }}"
      id: "{{ rocket_chat_mongodb_gpg_key }}"
    when: ansible_os_family == "Debian"
    tags: repo

  - name: Ensure the MongoDB repository is present
    vars:
      rocket_chat_mongodb_apt_repo: "deb http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse"  # Exemple pour Ubuntu 20.04 (Focal
    apt_repository:
      repo: "{{ rocket_chat_mongodb_apt_repo }}"
      state: present
    when: ansible_os_family == "Debian"
    tags: repo

  - name: Ensure MongoDB Server is present
    package:
      name: "{{ rocket_chat_mongodb_packages }}"
      state: present

  - name: Deploy MongoDB service configuration
    template:
      src: "{{ rocket_chat_mongodb_config_template }}"
      dest: /etc/mongod.conf
    notify: Restart the MongoDB service

  - meta: flush_handlers

  - name: Ensure the MongoDB service is started/enabled
    service: name=mongod state=started enabled=yes
